-- ============================

-- Este archivo se ha creado con la utilidad dblook de Derby.
-- Registro de hora: 2015-03-05 01:28:30.615
-- Base de datos origen: C:\Users\miguel\.netbeans-derby\bibliotecavirtual
-- URL de conexión: jdbc:derby:C:\Users\miguel\.netbeans-derby\bibliotecavirtual;user=mike;password=123
-- appendLogs: false

-- ----------------------------------------------
-- Sentencias DDL para esquemas
-- ----------------------------------------------

CREATE SCHEMA "MIKE";

-- ----------------------------------------------
-- Sentencias DDL para tablas
-- ----------------------------------------------

CREATE TABLE "MIKE"."ROL" ("IDROL" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "ROL" VARCHAR(50) NOT NULL);

CREATE TABLE "MIKE"."MATERIAL_ADICIONAL" ("IDMATERIAL_ADICIONAL" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "ARCHIVO" VARCHAR(100) NOT NULL, "IDTESIS" INTEGER NOT NULL, "TIPO_ARCHIVO" INTEGER NOT NULL);

CREATE TABLE "MIKE"."INSTITUCION_ADSCRIPCION" ("IDINSTITUCION_ADSCRIPCION" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NOMBRE" VARCHAR(40) NOT NULL);

CREATE TABLE "MIKE"."SUBDISCIPLINA" ("IDSUBDISCIPLINA" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NOMBRE" VARCHAR(50) NOT NULL);

CREATE TABLE "MIKE"."PERMISO_ROL" ("IDROL" INTEGER, "IDPERMISO" INTEGER NOT NULL);

CREATE TABLE "MIKE"."TESIS" ("IDTESIS" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "TITULO" VARCHAR(30) NOT NULL, "AUTOR_TESIS" VARCHAR(60) NOT NULL, "GRADO_OBTENIDO" INTEGER, "ANIO_TITULACION" INTEGER NOT NULL, "IDINSTITUCION_ADSCRIPCION" INTEGER DEFAULT 0, "DIRECTOR_TESIS" VARCHAR(70) NOT NULL, "CONDICION_SITIO" VARCHAR(150) NOT NULL, "IDESTADO" INTEGER DEFAULT 0, "IDDISCIPLINA" INTEGER NOT NULL, "IDSUBDISCIPLINA" INTEGER DEFAULT 0,"IDESPECIE" INTEGER DEFAULT 0, "ARCHIVO_TESIS" BLOB, "ESTATUS" INTEGER NOT NULL DEFAULT 1, "FECHA_REG" DATE NOT NULL);

CREATE TABLE "MIKE"."DISCIPLINA" ("IDDISCIPLINA" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "DISCIPLINA" VARCHAR(60) NOT NULL);

CREATE TABLE "MIKE"."CALIFICACION" ("IDCALIFICACION" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "CALIFICACION" DOUBLE NOT NULL, "IDUSUARIO" INTEGER NOT NULL, "IDTESIS" INTEGER NOT NULL, "FECHA_REG" DATE NOT NULL);

CREATE TABLE "MIKE"."ESTADO" ("IDESTADO" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NOMBRE" VARCHAR(30) NOT NULL);

CREATE TABLE "MIKE"."PERMISO" ("IDPERMISO" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "MODULO" VARCHAR(30) NOT NULL, "PERMISO" INTEGER NOT NULL);

CREATE TABLE "MIKE"."ESPECIE_TESIS" ("IDESPECIE_TESIS" INTEGER NOT NULL, "IDTESIS" INTEGER NOT NULL, "IDESPACIE" INTEGER NOT NULL);

CREATE TABLE "MIKE"."USUARIO" ("IDUSUARIO" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NOMBRE" VARCHAR(70) NOT NULL, "USUARIO" VARCHAR(20) NOT NULL, "PASSWORD" VARCHAR(300) NOT NULL, "FECHA_REG" DATE NOT NULL, "ESTATUS" INTEGER NOT NULL, "CORREO" VARCHAR(40) NOT NULL, "IDPAIS" INTEGER NOT NULL, "IDROL" INTEGER NOT NULL);

CREATE TABLE "MIKE"."COMENTARIO" ("IDCOMENTARIO" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "COMENTARIO" VARCHAR(200) NOT NULL, "IDTESIS" INTEGER, "IDUSUARIO" INTEGER, "FECHA_REG" DATE, "TIPO_COMENTARIO" INTEGER NOT NULL, "ESTATUS" INTEGER NOT NULL DEFAULT 0);

CREATE TABLE "MIKE"."BITACORA" ("IDBITACORA" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "IDUSUARIO" INTEGER, "IP" VARCHAR(20) NOT NULL, "FECHA_REG" DATE NOT NULL, "IDPAIS" INTEGER NOT NULL, "IDTESIS" INTEGER);

CREATE TABLE "MIKE"."PAIS" ("IDPAIS" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NOMBRE" VARCHAR(50) NOT NULL);

CREATE TABLE "MIKE"."CONTADOR" ("IDCONTADOR" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NUMERO_VISITAS" BIGINT NOT NULL);

CREATE TABLE "MIKE"."ESPECIE" ("IDESPECIE" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NOMBRE" VARCHAR(60) NOT NULL);

-- ----------------------------------------------
-- Sentencias DDL para claves
-- ----------------------------------------------

-- PRIMARY/UNIQUE
ALTER TABLE "MIKE"."ESPECIE" ADD CONSTRAINT "UQ_ESPECIE_NOMBRE" UNIQUE ("NOMBRE");

ALTER TABLE "MIKE"."ESPECIE" ADD CONSTRAINT "PK_ESPECIE" PRIMARY KEY ("IDESPECIE");

ALTER TABLE "MIKE"."ROL" ADD CONSTRAINT "PK_ROL" PRIMARY KEY ("IDROL");

ALTER TABLE "MIKE"."PAIS" ADD CONSTRAINT "UQ_PAIS_NOMBRE" UNIQUE ("NOMBRE");

ALTER TABLE "MIKE"."PAIS" ADD CONSTRAINT "PK_PAIS" PRIMARY KEY ("IDPAIS");

ALTER TABLE "MIKE"."PERMISO" ADD CONSTRAINT "UQ_PERMISO_MODULO" UNIQUE ("MODULO");

ALTER TABLE "MIKE"."PERMISO" ADD CONSTRAINT "PK_PERMISO" PRIMARY KEY ("IDPERMISO");

ALTER TABLE "MIKE"."ESPECIE_TESIS" ADD CONSTRAINT "PK_TESIS_ESPECIE" PRIMARY KEY ("IDESPECIE_TESIS");

ALTER TABLE "MIKE"."ESTADO" ADD CONSTRAINT "UQ_ESTADO_NOMBRE" UNIQUE ("NOMBRE");

ALTER TABLE "MIKE"."ESTADO" ADD CONSTRAINT "PK_ESTADO" PRIMARY KEY ("IDESTADO");

ALTER TABLE "MIKE"."SUBDISCIPLINA" ADD CONSTRAINT "PK_SUBDISCIPLINA" PRIMARY KEY ("IDSUBDISCIPLINA");

ALTER TABLE "MIKE"."COMENTARIO" ADD CONSTRAINT "PK_COMENTARIO" PRIMARY KEY ("IDCOMENTARIO");

ALTER TABLE "MIKE"."BITACORA" ADD CONSTRAINT "PK_BITACORA" PRIMARY KEY ("IDBITACORA");

ALTER TABLE "MIKE"."INSTITUCION_ADSCRIPCION" ADD CONSTRAINT "PK_INSTITUCION_ADSCRIPCION" PRIMARY KEY ("IDINSTITUCION_ADSCRIPCION");

ALTER TABLE "MIKE"."TESIS" ADD CONSTRAINT "PK_TESIS" PRIMARY KEY ("IDTESIS");

ALTER TABLE "MIKE"."MATERIAL_ADICIONAL" ADD CONSTRAINT "PK_MATERIAL_ADICIONAL" PRIMARY KEY ("IDMATERIAL_ADICIONAL");

ALTER TABLE "MIKE"."CONTADOR" ADD CONSTRAINT "PK_CONTADOR" PRIMARY KEY ("IDCONTADOR");

ALTER TABLE "MIKE"."CALIFICACION" ADD CONSTRAINT "PK_CALIFICACION" PRIMARY KEY ("IDCALIFICACION");

ALTER TABLE "MIKE"."USUARIO" ADD CONSTRAINT "UQ_USUARIO_USUARIO" UNIQUE ("USUARIO");

ALTER TABLE "MIKE"."USUARIO" ADD CONSTRAINT "UQ_USUARIO_NOMBRE" UNIQUE ("NOMBRE");

ALTER TABLE "MIKE"."USUARIO" ADD CONSTRAINT "PK_USUARIO" PRIMARY KEY ("IDUSUARIO");

ALTER TABLE "MIKE"."DISCIPLINA" ADD CONSTRAINT "UQ_DISCIPLINA_DISCIPLINA" UNIQUE ("DISCIPLINA");

ALTER TABLE "MIKE"."DISCIPLINA" ADD CONSTRAINT "PK_DISCIPLINA" PRIMARY KEY ("IDDISCIPLINA");

-- FOREIGN
ALTER TABLE "MIKE"."PERMISO_ROL" ADD CONSTRAINT "FK_PERMISO_ROL_ROL" FOREIGN KEY ("IDROL") REFERENCES "MIKE"."ROL" ("IDROL") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "MIKE"."PERMISO_ROL" ADD CONSTRAINT "FK_PERMISO_ROL_PERMISO" FOREIGN KEY ("IDPERMISO") REFERENCES "MIKE"."PERMISO" ("IDPERMISO") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "MIKE"."ESPECIE_TESIS" ADD CONSTRAINT "FK_ESPECIE_TESIS_ESPECIE" FOREIGN KEY ("IDESPACIE") REFERENCES "MIKE"."ESPECIE" ("IDESPECIE") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "MIKE"."COMENTARIO" ADD CONSTRAINT "FK_COMENTARIO_USUARIO" FOREIGN KEY ("IDUSUARIO") REFERENCES "MIKE"."USUARIO" ("IDUSUARIO") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "MIKE"."BITACORA" ADD CONSTRAINT "FK_BITACORA_PAIS" FOREIGN KEY ("IDPAIS") REFERENCES "MIKE"."PAIS" ("IDPAIS") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "MIKE"."BITACORA" ADD CONSTRAINT "FK_BITACORA_USUARIO" FOREIGN KEY ("IDUSUARIO") REFERENCES "MIKE"."USUARIO" ("IDUSUARIO") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "MIKE"."CALIFICACION" ADD CONSTRAINT "FK_CALIFICACION_USUARIO" FOREIGN KEY ("IDUSUARIO") REFERENCES "MIKE"."USUARIO" ("IDUSUARIO") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "MIKE"."USUARIO" ADD CONSTRAINT "FK_USUARIO_PAIS" FOREIGN KEY ("IDPAIS") REFERENCES "MIKE"."PAIS" ("IDPAIS") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "MIKE"."USUARIO" ADD CONSTRAINT "FK_USUARIO_ROL" FOREIGN KEY ("IDROL") REFERENCES "MIKE"."ROL" ("IDROL") ON DELETE NO ACTION ON UPDATE NO ACTION;

