DROP TABLE autor
;
DROP TABLE calificacion
;
DROP TABLE catalogo
;
DROP TABLE comentario
;
DROP TABLE director
;
DROP TABLE documento
;
DROP TABLE entidadfederativa
;
DROP TABLE menu
;
DROP TABLE municipio
;
DROP TABLE pais
;
DROP TABLE parametro
;
DROP TABLE permiso
;
DROP TABLE persona
;
DROP TABLE rol
;
DROP TABLE rolPermiso
;
DROP TABLE sugerencia
;
DROP TABLE tesis
;
DROP TABLE tipoDocumento
;
DROP TABLE usuario
;
DROP TABLE visita
;

CREATE TABLE autor ( 
	idAutor INTEGER NOT NULL,
	fechaDebut DATE,
	alias VARCHAR(255),
	idInstitucion INTEGER,
	idGradoAcademico INTEGER,
	idProfesion INTEGER
)
;

CREATE TABLE calificacion ( 
	idCalificacion INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	idTesis INTEGER,
	idUsuario INTEGER,
	tiempoCreacion TIMESTAMP,
	comentario VARCHAR(255),
	calificacion INTEGER
)
;

CREATE TABLE catalogo ( 
	idCatalogo INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	idCategoria INTEGER DEFAULT NULL,
	nombre VARCHAR(255)
)
;

CREATE TABLE comentario ( 
	idComentario INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	idTesis INTEGER,
	idUsuario INTEGER,
	tiempoCreacion TIMESTAMP,
	comentario VARCHAR(1000)
)
;

CREATE TABLE director ( 
	idDirector INTEGER NOT NULL,
	idInstitucion INTEGER,
	idGradoAcademico INTEGER,
	idProfesion INTEGER
)
;

CREATE TABLE documento ( 
	idTesis INTEGER NOT NULL,
	idTipoDocumento INTEGER NOT NULL,
	nombre VARCHAR(50),
	url VARCHAR(255)
)
;

CREATE TABLE entidadfederativa ( 
	idEntidadFederativa INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nombre VARCHAR(50),
	clave VARCHAR(4),
	idPais INTEGER
)
;

CREATE TABLE menu ( 
	idMenu INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nombre VARCHAR(255),
	idMenuContenedor INTEGER,
	orden INTEGER,
	idTipo INTEGER,
	enlace VARCHAR(255)
)
;

CREATE TABLE municipio ( 
	idMunicipio INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	idEntidadFederativa INTEGER NOT NULL,
	nombre VARCHAR(60),
	clave VARCHAR(5)
)
;

CREATE TABLE pais ( 
	idPais INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nombre VARCHAR(50),
	nacionalidad VARCHAR(50),
	codigo VARCHAR(2)
)
;

CREATE TABLE parametro ( 
	idParametro INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	idTipo CHAR(1) DEFAULT 'U' NOT NULL,
	nombre VARCHAR(50),
	descripcion VARCHAR(255),
	valor CLOB,
	idCategoria INTEGER
)
;

CREATE TABLE permiso ( 
	idPermiso INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nombre VARCHAR(50),
	descripcion VARCHAR(255),
	permisos VARCHAR(255),
	idMenu INTEGER
)
;

CREATE TABLE persona ( 
	idPersona INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	idMunicipio INTEGER,
	nombre VARCHAR(50),
	apellidos VARCHAR(50),
	fechaNacimiento DATE,
	email VARCHAR(50),
	idPais INTEGER,
	idEntidadFederativa INTEGER,
	curp VARCHAR(18)
)
;

CREATE TABLE rol ( 
	idRol INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nombre VARCHAR(50),
	idEstatus INTEGER NOT NULL,
	tiempoSesion INTEGER,
	spMiperfil CHAR(1) DEFAULT 'N'
)
;

CREATE TABLE rolPermiso ( 
	idRol INTEGER NOT NULL,
	idPermiso INTEGER NOT NULL
)
;

CREATE TABLE sugerencia ( 
	idSugerencia INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	sugerencia VARCHAR(1000),
	tiempoCreacion TIMESTAMP,
	idUsuario INTEGER
)
;

CREATE TABLE tesis ( 
	idTesis INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	titulo VARCHAR(255),
	idPais INTEGER,
	idEntidadFederativa INTEGER,
	idDisciplina INTEGER,
	idSubdisciplina INTEGER,
	idInstitucion INTEGER,
	idGrado INTEGER,
	idEspecie INTEGER,
	idDirector INTEGER,
	condiciones VARCHAR(255),
	anio INTEGER,
	idAutor INTEGER,
	sintesis VARCHAR(8000)
)
;

CREATE TABLE tipoDocumento ( 
	idTipoDocumento INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	descripcion VARCHAR(50),
	extensiones VARCHAR(50)
)
;

CREATE TABLE usuario ( 
	idUsuario INTEGER NOT NULL,
	idRol INTEGER,
	tiempoRegistro TIMESTAMP,
	username VARCHAR(25),
	password VARCHAR(50)
)
;

CREATE TABLE visita ( 
	idVisita INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	tiempoVisita TIMESTAMP,
	idUsuario INTEGER,
	idTesis INTEGER,
	idPais INTEGER
)
;

ALTER TABLE autor ADD CONSTRAINT PK__comentar__C74515DA2C6D9XXS 
	PRIMARY KEY (idautor)
;


ALTER TABLE calificacion ADD CONSTRAINT PK__comentar__C74515DA2C6D93CE 
	PRIMARY KEY (idCalificacion)
;


ALTER TABLE catalogo ADD CONSTRAINT PK__catalogo__C615E0E807020F21 
	PRIMARY KEY (idCatalogo)
;


ALTER TABLE comentario ADD CONSTRAINT PK__comentar__C74515DA26B4BA78 
	PRIMARY KEY (idComentario)
;


ALTER TABLE director ADD CONSTRAINT PK__director__92E1D6EE66CF3F8D 
	PRIMARY KEY (idDirector)
;


ALTER TABLE documento ADD CONSTRAINT PK__document__683FAC721D2B503E 
	PRIMARY KEY (idTesis, idTipoDocumento)
;


ALTER TABLE entidadfederativa ADD CONSTRAINT PK__entidadF__464652044E7E8A33 
	PRIMARY KEY (idEntidadFederativa)
;


ALTER TABLE menu ADD CONSTRAINT PK__menu__C26AF4831209AD79 
	PRIMARY KEY (idMenu)
;


ALTER TABLE municipio ADD CONSTRAINT PK__municipi__FD10E4000BC6C43E 
	PRIMARY KEY (idMunicipio)
;


ALTER TABLE pais ADD CONSTRAINT PK__pais__BD2285E31920BF5C 
	PRIMARY KEY (idPais)
;


ALTER TABLE parametro ADD CONSTRAINT PK__parametr__9C816E5F3CD905C1 
	PRIMARY KEY (idParametro)
;


ALTER TABLE permiso ADD CONSTRAINT PK__permiso__06A584864589517F 
	PRIMARY KEY (idPermiso)
;


ALTER TABLE persona ADD CONSTRAINT PK__personal__D840C9FD6AFACD50 
	PRIMARY KEY (idPersona)
;


ALTER TABLE rol ADD CONSTRAINT PK__rol__3C872F766D9742D9 
	PRIMARY KEY (idRol)
;


ALTER TABLE rolPermiso ADD CONSTRAINT PK__perfil__4CED773E42ACE4D4 
	PRIMARY KEY (idRol, idPermiso)
;


ALTER TABLE sugerencia ADD CONSTRAINT PK__sugerenc__A4668EAA11B99D92 
	PRIMARY KEY (idSugerencia)
;


ALTER TABLE tesis ADD CONSTRAINT PK__tesis__2E2073ED6E706155 
	PRIMARY KEY (idTesis)
;


ALTER TABLE tipoDocumento ADD CONSTRAINT PK__tipoDocu__61FDF9F520FBE122 
	PRIMARY KEY (idTipoDocumento)
;


ALTER TABLE usuario ADD CONSTRAINT PK__usuario__645723A60C00C43C 
	PRIMARY KEY (idUsuario)
;


ALTER TABLE visita ADD CONSTRAINT PK__visita__0F55DBEC167E52AF 
	PRIMARY KEY (idVisita)
;

DELETE FROM CATALOGO;
INSERT INTO CATALOGO VALUES
    (1,NULL,'Paises'),
    (101,1,'Mexico'),(102,1,'Estados Unidos de America'),(103,1,'Canada'),
    (2,NULL,'Entidades federativas'),
    (201,2,'Veracruz'),(202,2,'Puebla'),(203,2,'Chiapas'),
    (3,NULL,'Disciplinas'),
    (301,3,'Estudio de campo'),(302,3,'Analisis laboratorio'),
    (4,NULL,'Subdisciplinas'),
    (401,4,'Comportamiento'),
    (5,NULL,'Instituciones'),
    (501,5,'UV'),(502,5,'Inecol'),
    (6,NULL,'Grado obtenido'),
    (601,6,'Licenciatura'),(602,6,'Maestria'),(603,6,'Doctorado'),
    (7,NULL,'Especies de primates'),
    (701,7,'Mono'),(702,7,'Gorila'),
    (8,NULL,'Directores'),
    (801,8,'Jose C. Vales'),(802,8,'Cristina Fernandez Cubas'),
    (9,NULL,'Autores'),
    (901,9,'Blue Jeans'),(902,9,'James Kakalios'),(903,9,'Betty Smith');

DELETE FROM TESIS;
INSERT INTO TESIS VALUES
    (1,'Los primates mexicanos mas sociables',101,203,301,401,502,602,701,801,
     'Estudio en condiciones naturales',2014,901,'Tesis basada en el comportamiento social de los primates'),
    (2,'La defensa territorial de los machos alfa',102,201,302,401,501,601,702,802,
     'Estudio en condiciones de competencia',2010,902,'Analisis de agresividad de los primates');